### ISSUE TITLE
Dependence on casing of project declarations

### ISSUE THREAD

**Issue by Krzmbrzl** [molpro/dependency-manager#2]
Via this line
https://github.com/molpro/dependency-manager/blob/1b0e09a13213b39d5af4ab1e5bd4fc33dd69e22a/cmake/DependencyManager.cmake#L714
we rely on having matched the casing of the given sub-project's (dependency) `project` declaration with the name we gave the dependency when declaring it via `DependencyManager_Declare`. 

This can become problematic as the entire system relies on the injected code being run once the respective dependency is made available via `add_subdirectory` and if that doesn't happen, a misleading error message is printed to the user.

There should be a mechanism that fetches the proper spelling of the project.

**Comment by pjknowles** [comment]
Thank you; yes, aware of this problem, for which the workaround has been to use only lower case.

For hdf5 in Molpro, it shouldn't be necessary to use dependency-manager - simple FetchContent will be enough, since editing of hdf5 source would not be envisioned.

**Comment by Krzmbrzl** [comment]
> Thank you; yes, aware of this problem, for which the workaround has been to use only lower case.

That only works as long as one actually has direct control over the dependencies - which I guess is a fair assumption given the idea behind this project :thinking: 

> For hdf5 in Molpro, it shouldn't be necessary to use dependency-manager - simple FetchContent will be enough, since editing of hdf5 source would not be envisioned.

Alright. I almost have it figured out though. If the fix for this issue works as I think it should, I can create a PR here and have things work with dependency manager as well. Otherwise, I'll fall back to FetchContent. We'll see :)
